### ISSUE TITLE
TypeScript definitions?

### ISSUE THREAD

**Issue by Zorgatone** [zachfitz/Ionic-Material#152]
Did anybody make any TypeScript definitions for ionic-material yet?

**Comment by BioPhoton** [comment]
Would also need this.

**Comment by macklus** [comment]
+1 on this

**Comment by christmo** [comment]
+1 yes we need this in Angular2

**Comment by dusdong** [comment]
+1 on this

**Comment by Zorgatone** [comment]
I don't need this anymore with Ionic 2/3+

**Comment by macklus** [comment]
I open a new issue on #228

**Comment by satishSKY** [comment]
No need in ionic 3
