### ISSUE TITLE
Inject?

### ISSUE THREAD

**Issue by schutzsmith** [zachfitz/Ionic-Material#184]
I don't understand what "Step 4: Inject Ionic & Ionic Material into your Ionic App" means. Where are we placing this code? How does it need to be modified?

Thanks!

**Comment by iguatemigarin** [comment]
Hey, schutzmith!

In practice it means this:
```HTML
<!-- a-page.html -->
<body ng-app="myApp">
...
</body>
```
```JavaScript
// a-module.module.js
angular.module('myApp', ['ionic','ionic-material']);
```
It means that you should tell AngularJS that your app "myApp" will use "ionic" and "ionic-material".
If this is not clear to you, I strongly suggest that you read the AngularJS documentation on modules: https://docs.angularjs.org/guide/module

Hope it helps,

Cheers

**Comment by ekoom** [comment]
Thanks, this is exactly what I was looking for.  
The Step 4 was unclear since this a new start for me with ionic 2 and Angular 2.
