### ISSUE TITLE
Available for IONIC 2?

### ISSUE THREAD

**Issue by tnqsoft** [zachfitz/Ionic-Material#216]
I meet ionic-material project when search on Google. And amazing with demo. I very like it. But I have project with IONIC 2. Now, we have version available with IONIC 2?.

**Comment by cvrloz** [comment]
I think this repo is dead, there are not any commits beyond october 2015

**Comment by rendy44** [comment]
@cvrloz you're right, i don't think this repo has future.
I think http://ionicmaterialdesign.com/ looks better

**Comment by cvrloz** [comment]
@rendy44 the bad thing about that is that's not free :(
