### ISSUE TITLE
Feature - fab menu

### ISSUE THREAD

**Issue by mavrick** [zachfitz/Ionic-Material#42]
Would love to see the floating action buttons expanded on and incorporate a menu system like: https://github.com/nobitagit/ng-material-floating-button

Awesome library btw! Making some awesome prototype apps atm. <3

Cheers

**Comment by shaulhadar** [comment]
hi mavrick, this is a great idea. I actually already implemented this in my work in progress...could be an amazing addition:)

**Comment by giovanniorigins** [comment]
I think this would be an awesome addition!

**Comment by Tlvenn** [comment]
The strange thing is I swear I saw this on the demo / documentation area yesterday or so and now I cant seem to find it... Did i dream it @zachsoft ?
