### ISSUE TITLE
Why we have call ink-effect manually?

### ISSUE THREAD

**Issue by patlux** [zachfitz/Ionic-Material#70]
Why we have to call in every controller the ink function instead of using a directive to handle this?

Like this directive: https://github.com/nelsoncash/angular-ripple

**Comment by patlux** [comment]
A workaround solution for me was to create a directive like:

```
  (function() {
    var ionContentDirective;

    /* @ngInject */
    ionContentDirective = function() {

      /* @ngInject */
      var controller, directive;
      controller = function(ionicMaterialInk) {
        return ionicMaterialInk.displayEffect();
      };
      directive = {
        controller: controller,
        restrict: 'EA'
      };
      return directive;
    };
    return angular.module('app.directives').directive('ionContent', ionContentDirective);
  })();

```

This directive call the ink function on all ion-content tags.

**Comment by shaulhadar** [comment]
Looks Great MAn!

**Comment by delta98** [comment]
@patlux it needs to be called manually as it depends on the DOM being ready. Agreed there needs to be a better way. 

If you could create a pull request with your directive I can test and merge it in if everyone agrees.

**Comment by insekticid** [comment]
it works! thx

**Comment by kashban** [comment]
Good idea, but as @delta98 pointed out the function needs to be called when DOM is ready. On views with ngRepeat you have to call it after the last element has been rendered, otherwise you'll get an error and no effects. At least not until the view gets active a second time.

**Comment by EeKay** [comment]
+1 kashban's code worked like a charm. the code was in https://github.com/zachsoft/Ionic-Material/issues/46 also, where a SO link is included to the inspiring code..
